### ISSUE TITLE
Canvas prompts do not display standard

### ISSUE THREAD

**Issue by siwelwerd** [StevenClontz/masterit#3]
Many instructors (i.e. me) like to display the standard number on assessments so that students know which problems they can skip.  However, when a Canvas quiz is created and pulls a question from the question bank, the displayed title is simply "Question 1" or similar.  It's not clear if this is a Canvas "feature" or a feature of the QTI standard. 

![canvas bug](https://user-images.githubusercontent.com/30658947/89192118-86ea3600-d569-11ea-97e2-7f169874813d.png)

**Comment by StevenClontz** [comment]
They are titled in the Question Bank, but not when the question appears in a quiz. I'd considered just having separate quizzes for each standard, but I'm not sure of the logistics of this.

It's not hard to inject the exercise metadata into the item's content if we want. Probably this should be configurable, but the default will be whatever we think makes sense for the fall.

**Comment by siwelwerd** [comment]
Agreed it's not hard to fix. But I didn't want to fix it in the CoCalc until I knew how to get those changes into this repository easily.
